package com.epam.hack.ProjectG;

import static com.epam.hack.model.enums.AgeGroup.EIGHTEEN_TO_TWENTY;
import static com.epam.hack.model.enums.Gender.F;
import static com.epam.hack.model.enums.Gender.M;
import static org.hamcrest.CoreMatchers.containsString;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

import java.util.List;

import org.junit.jupiter.api.Test;

import com.epam.hack.app.bo.GoalGenerator;
import com.epam.hack.model.Goal;
import com.epam.hack.model.UserProfile;

public class GoalGeneratorTest {

	private GoalGenerator goalGenerator = new GoalGenerator();
	
	@Test
	public void testGoalGeneratorForEarlyStage() {
		UserProfile unmarriedGirl = new UserProfile(F, EIGHTEEN_TO_TWENTY, false);
		UserProfile marriedGirl = new UserProfile(F, EIGHTEEN_TO_TWENTY, true);
		UserProfile unmarriedBoy = new UserProfile(M, EIGHTEEN_TO_TWENTY, false);
		UserProfile marriedBoy = new UserProfile(M, EIGHTEEN_TO_TWENTY, true);
		
		List<Goal> goals = goalGenerator.getAutoGeneratedGoal(unmarriedGirl);
		assertThat(goals.size(), is(1));
		
		Goal goal = goals.get(0);
		assertThat(goal.getName(), containsString("Plan for Marriage Expenses"));
		assertThat(goal.getTargetMonth(), is(6));
	}
	
}
